// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwgeAdqTG4DKG8nX_qlJtD8YxLlK3CJuw',
    appId: '1:764339883783:web:b18f28e7a43dee618d7fa2',
    messagingSenderId: '764339883783',
    projectId: 'registroconductaapp',
    authDomain: 'registroconductaapp.firebaseapp.com',
    storageBucket: 'registroconductaapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJUot8zYbCIZVxEaVo2lcOG7ZpDQrlOQg',
    appId: '1:764339883783:android:db661fd5f24c10ce8d7fa2',
    messagingSenderId: '764339883783',
    projectId: 'registroconductaapp',
    storageBucket: 'registroconductaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9mP0VdxSmZmOZvdDgL1lpN6q-0ke2uZk',
    appId: '1:764339883783:ios:10395dc7b4d3e8c78d7fa2',
    messagingSenderId: '764339883783',
    projectId: 'registroconductaapp',
    storageBucket: 'registroconductaapp.appspot.com',
    iosClientId: '764339883783-vuhn4pq6f6cfjtauug7r2cr8kruquqo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.registroConductaAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9mP0VdxSmZmOZvdDgL1lpN6q-0ke2uZk',
    appId: '1:764339883783:ios:10395dc7b4d3e8c78d7fa2',
    messagingSenderId: '764339883783',
    projectId: 'registroconductaapp',
    storageBucket: 'registroconductaapp.appspot.com',
    iosClientId: '764339883783-vuhn4pq6f6cfjtauug7r2cr8kruquqo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.registroConductaAppV2',
  );
}
